baseURL = "https://tarinyoom.io/"
locale = "en-us"
title = "tarinyoom.io"

enableRobotsTXT = true
disableKinds = ["taxonomy", "term", "rss", "sitemap"]

[markup]
  [markup.goldmark.renderer]
    unsafe = true

[params]
  description = "A personal blog for some personal projects."
  author = "Adam Reynolds"
